name: lms
services:
  api:
    container_name: lms_api
    build: ./apps/api
    env_file:
      - ./apps/api/.env.production
    ports:
      - "3001:3001"
    networks:
      - lms_network

  web:
    container_name: lms_web
    build: ./apps/web
    env_file:
      - ./apps/web/.env.production
    ports:
      - "3000:3000"
    depends_on:
      - api
    networks:
      - lms_network

networks:
  lms_network:
    driver: bridge
