services:
  api:
    container_name: lms_api
    build: .
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:prod

  mongo:
    container_name: lms_mongo
    image: mongo:7
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
